Remove obsolete Rubocop settings
Remove settings which are removed in Rubocop v0.51 so that Hound works
correctly.  The executable used to output:

Error: The `Lint/InvalidCharacterLiteral` cop has been removed since it
was never being actually triggered.
(obsolete configuration found in .rubocop.yml, please update it)
Error: obsolete parameter EnforcedStyle (for Style/Encoding) found in
.rubocop.yml
Style/Encoding no longer supports styles. The "never" behavior is always
assumed.
obsolete parameter SupportedStyles (for Style/Encoding) found in
.rubocop.yml
Style/Encoding no longer supports styles. The "never" behavior is always
assumed.